source("managePackages.R")
source("utils.R")
source("read_data.R")

ARIMA_forecast(data_1)
ARIMA_forecast(data_2)
ARIMA_forecast(data_3)
ARIMA_forecast(data_4)
ARIMA_forecast(data_5)
ARIMA_forecast(data_6)
